### ISSUE TITLE
Blinds: stage 8 code fails main() at boot with IDFError('Invalid argument')

### ISSUE THREAD

**Issue by heikkileivo** [heikkileivo/circuitpython-ha-blinds#103]
Found at stage 8 gate #56, run 1, step 1 (2026-09-15, `main` at `a6ab0ba`).

**What happened.** Middle was deployed at 13:40:24. From then on every boot failed `main()` twice, then restarted with `restart_loop`, about every 30 s. It never connected to MQTT: the gate logger, subscribed to its `<did>/#`, saw no `online` after the deploy's `offline` at 13:40:28. The serial capture showed the same four lines on each of six cycles:

```
13:40:51.292 main() failed: IDFError('Invalid argument',)
13:40:51.306 Running main() again in 10 s...
13:41:01.310 main() failed: IDFError('Invalid argument',)
13:41:01.310 main() keeps failing, restarting.
```

Middle was restored to its stage 7 backup `2026-09-15_13-40-24` at 13:46:21. It was online at 13:46:26, showing `open`, with reset cause `restart_loop`.

**What's known:**
- `IDFError('Invalid argument')` is `ESP_ERR_INVALID_ARG` from an ESP-IDF call. The restart loop prints only `repr(e)`, so there's no traceback.
- **The first run's failure is the real one, and where it happens is unknown.** The capture reconnects only after 15 s of silence, so it missed the first 15 s of each boot, and with them everything the first run printed before it failed.
- **The second run fails within 4 ms of the 10 s delay, and prints nothing.** So it fails in `arm_watchdog()`, before its print. A likely cause, unverified: on a later run the watchdog's mode is already RESET, so setting `timeout` reconfigures it. That subscribes the task to ESP-IDF's task watchdog again with `esp_task_wdt_add()`, which returns `ESP_ERR_INVALID_ARG` for a task already subscribed. If so, it predates stage 8: no failed `main()` ever gets a real retry, and the restart loop restarts after the first failure. #43's restart-loop check used a build that failed every run anyway, so it couldn't show this.
- The boot path changes since stage 7 (`35378e1`):
  - #101 adds the two temperature sensors, which grows the discovery payload from 2,784 B to 3,502 B. That's under the 4,096 B budget, and the payload goes out only after `online`, which never arrived.
  - #102 adds `service_mqtt`'s pacing, `MoveControl` and `Tracker.can_pause`.
- All 228 host tests pass on `a6ab0ba`, including the CircuitPython syntax check over every deployed file.
- Left and Right weren't touched, and still run stage 7.

**Next:** a traceback from the device. For example, a throwaway `code.py` that prints the first failure with `traceback.print_exception()`, and captures serial from the power-on. That's a throwaway upload, so it needs Heikki's OK.

**Comment by heikkileivo** [comment]
## Diagnosed: 2026-09-15, 14:02 on Middle (Heikki OK'd the temporary `code.py`)

The temporary `code.py` was `main`'s, with a restart loop that:
- prints the first failure's traceback
- calls `arm_watchdog()` a second time
- repeats both every 5 s instead of restarting

It went up right after a `deploy.py` of `main`. The serial output:

```
Traceback (most recent call last):
  File "code.py", line 495, in <module>
  File "asyncio/core.py", line 317, in run
  File "asyncio/core.py", line 276, in run_until_complete
  File "asyncio/core.py", line 261, in run_until_complete
  File "code.py", line 273, in main
  File "code.py", line 314, in run_blind
  File "components.py", line 10, in blinds_discovery
  File "components.py", line 87, in add_components
AttributeError: 'str' object has no attribute 'capitalize'
arm_watchdog() again failed:
Traceback (most recent call last):
  File "code.py", line 471, in diag_loop
  File "code.py", line 92, in arm_watchdog
espidf.IDFError: Invalid argument
```

**There are two bugs:**

1. **The boot failure comes from #101, not #102.** `components.py:87` names the temperature sensors with `servo.capitalize()`, and CircuitPython's `str` has no `capitalize()`.
   - CPython has it, so the host tests pass.
   - It raises in `blinds_discovery()`, before the Wi-Fi connect, so every boot fails.
   - It's the only such call in the deployed code. I grepped for the `str` methods MicroPython leaves out, such as `title`, `zfill`, `ljust`/`rjust`, `isalnum` and `removeprefix`.
   - **Fix:** spell the two names out, "Lift temperature" and "Tilt temperature". A host test next to `test_circuitpython_syntax.py` could reject those methods in every deployed file, as #76's check does for f-strings.
2. **`arm_watchdog()` fails when it's called again.** That's what the `IDFError` in the report was. On a re-run the watchdog is already in RESET mode, and setting `microcontroller.watchdog.timeout` (`code.py:92`) then raises `espidf.IDFError: Invalid argument`.
   - So every failed `main()` fails again at once on its re-run, and the restart loop restarts after the first failure. That has been true since the restart loop came in.
   - The restart loop prints only `repr(e)`, which is why the report showed the second failure's error and never the first's.
   - **Fix:** arm only when the mode isn't RESET already, and just feed otherwise.
   - Printing the traceback instead of `repr(e)`, which `traceback` in CircuitPython 9.1 supports, would have shown bug 1 on the gate's first capture.

Middle was restored to its stage 7 backup `2026-09-15_13-40-24` at 14:04:12–14:04:26. It was online at 14:04:30, showing `open`. The gate #56 run starts again from step 1 once the fix is merged.
